# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from . import base, clients, exceptions, models, parsers
import importlib

__version__ = '2.0.0'
__author__ = 'HDHive Scraper'
MediaType = _models.MediaType
Website = _models.Website
MediaInfo = _models.MediaInfo
ResourceInfo = _models.ResourceInfo
SearchResult = _models.SearchResult
ShareUrlResult = _models.ShareUrlResult
UserInfo = _models.UserInfo
ResourceListResult = _models.ResourceListResult
Genre = _models.Genre
Season = _models.Season
HDHiveError = _exceptions.HDHiveError
AuthenticationError = _exceptions.AuthenticationError
LoginRequiredError = _exceptions.LoginRequiredError
TokenExpiredError = _exceptions.TokenExpiredError
MediaNotFoundError = _exceptions.MediaNotFoundError
ResourceNotFoundError = _exceptions.ResourceNotFoundError
ParseError = _exceptions.ParseError
RateLimitError = _exceptions.RateLimitError
NetworkError = _exceptions.NetworkError
PointsRequiredError = _exceptions.PointsRequiredError
ClientConfig = _base.ClientConfig
HDHiveClientBase = _base.HDHiveClientBase
AsyncHDHiveClientBase = _base.AsyncHDHiveClientBase
RequestsClient = _clients.RequestsClient
PlaywrightClient = _clients.PlaywrightClient
RSCParser = _parsers.RSCParser
def create_client(cookie: str, username: str, password: str, base_url: str, proxy: dict) -> RequestsClient:
    ...

def create_async_client(username: str, password: str, cookie: str, base_url: str, proxy: dict, headless: bool, state_file: str) -> PlaywrightClient:
    ...

__all__ = ['__version__', 'create_client', 'create_async_client', 'RequestsClient', 'PlaywrightClient', 'ClientConfig', 'HDHiveClientBase', 'AsyncHDHiveClientBase', 'MediaType', 'Website', 'MediaInfo', 'ResourceInfo', 'SearchResult', 'ShareUrlResult', 'UserInfo', 'ResourceListResult', 'Genre', 'Season', 'HDHiveError', 'AuthenticationError', 'LoginRequiredError', 'TokenExpiredError', 'MediaNotFoundError', 'ResourceNotFoundError', 'ParseError', 'RateLimitError', 'NetworkError', 'PointsRequiredError', 'RSCParser']

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import importlib
import time
import random
import jwt
import abc
import typing
import dataclasses
import re
import json
import logging
import urllib
import urllib.parse
import playwright
import playwright.async_api
import playwright.async_api.async_playwright
import playwright.async_api.Browser
import playwright.async_api.Page
import playwright.async_api.BrowserContext
import hdhive.parsers.RSCParser
import requests
import urllib3
import enum